name: Build Game

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: ["Windows Desktop", "Linux/X11", "macOS", "Android arm64"]

    steps:
      - uses: actions/checkout@v4

      - name: Build
        id: build
        uses: mlm-games/godot-build-action@v1.3.1
        with:
          EXPORT_PRESET_NAME: ${{ matrix.preset }}
          PROJECT_DIR: .                # if your project is in a subfolder
          GODOT_VER: "4.7.1-stable"                    # auto-detect latest stable 4.x
          DEBUG_MODE: "false"              # or "true"
          GODOT_PREVIEW_BUILDS: "false"    # set "true" to use preview builds
          EXPORT_DIR: builds
          INSTALL_BLENDER: "false"         # or "true" if your project has .blend files
          BLENDER_VERSION: "4.4.3"
          IMPORT_TIMEOUT: "60"
          VERBOSE_IMPORT: "true"
          BUTLER_UPLOAD: "false"           # set "true" to upload to itch
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          ITCH_USER_SLASH_GAME: yourname/yourgame

      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.preset }}-build
          path: ${{ steps.build.outputs.build }}
